<?php
/**
 * seo.
 */
$urls = array(
'https://p7ing.com/',
'https://p7ing.com/web',
'https://p7ing.com/wechat',
'https://p7ing.com/app',
'https://p7ing.com/case',
'https://p7ing.com/news',
'https://p7ing.com/about',
'https://p7ing.com/web_site_shop_web',
'https://p7ing.com/web_site_shop_b2b2c',
'https://p7ing.com/web_site_shop_sale',
'https://p7ing.com/web_site_company_web',
'https://p7ing.com/web_site_company_view',
'https://p7ing.com/web_site_company_sale',
'https://p7ing.com/web_site_company_all',
'https://p7ing.com/web_site_html5',
'https://p7ing.com/web_site_portal_web',
'https://p7ing.com/web_site_admin',
'https://p7ing.com/wechat_dev_public',
'https://p7ing.com/wechat_dev_small',
'https://p7ing.com/wechat_site_shop_web',
'https://p7ing.com/wechat_site_shop_b2b2c',
'https://p7ing.com/wechat_site_shop_sale',
'https://p7ing.com/wechat_dev_service',
'https://p7ing.com/soft_creat_app',
'https://p7ing.com/news?page=2',
'https://p7ing.com/news?page=3',
'https://p7ing.com/news?page=4',
'https://p7ing.com/news?page=5',
'https://p7ing.com/news?page=6',
'https://p7ing.com/news?page=7',
'https://p7ing.com/news?page=8',
'https://p7ing.com/news?page=9',
'https://p7ing.com/news?page=1',
'https://p7ing.com/news_info/13',
'https://p7ing.com/news_info/16',
'https://p7ing.com/case_info/1',
'https://p7ing.com/case_info/2',
'https://p7ing.com/case_info/3',
'https://p7ing.com/case_info/7',
'https://p7ing.com/case_info/11',
'https://p7ing.com/case_info/10',
'https://p7ing.com/case_info/9',
'https://p7ing.com/case_info/8',
'https://p7ing.com/news_info/76',
'https://p7ing.com/news_info/75',
'https://p7ing.com/news_info/74',
'https://p7ing.com/news_info/73',
'https://p7ing.com/news_info/72',
'https://p7ing.com/news_info/69',
'https://p7ing.com/news_info/71',
'https://p7ing.com/news_info/34',
'https://p7ing.com/news_info/33',
'https://p7ing.com/news_info/11',
'https://p7ing.com/news_info/17',
'https://p7ing.com/news_info/63',
'https://p7ing.com/news_info/57',
'https://p7ing.com/news_info/49',
'https://p7ing.com/news_info/39',
'https://p7ing.com/news_info/36',
'https://p7ing.com/news_info/35',
'https://p7ing.com/case/1',
'https://p7ing.com/case/2',
'https://p7ing.com/case/4',
'https://p7ing.com/case/5',
'https://p7ing.com/news/1',
'https://p7ing.com/news/2',
'https://p7ing.com/news/3',
'https://p7ing.com/news/4',
'https://p7ing.com/news/5',
'https://p7ing.com/news/6',
'https://p7ing.com/news_info/77',
'https://p7ing.com/news_info/10',
'https://p7ing.com/news_info/12',
'https://p7ing.com/news_info/9',
'https://p7ing.com/news_info/6',
'https://p7ing.com/news_info/8',
'https://p7ing.com/news_info/14',
'https://p7ing.com/news_info/15',
'https://p7ing.com/news_info/68',
'https://p7ing.com/news_info/70',
'https://p7ing.com/news_info/32',
'https://p7ing.com/news_info/27',
'https://p7ing.com/news_info/62',
'https://p7ing.com/news_info/64',
'https://p7ing.com/news_info/56',
'https://p7ing.com/news_info/58',
'https://p7ing.com/news_info/48',
'https://p7ing.com/news_info/50',
'https://p7ing.com/news_info/38',
'https://p7ing.com/news_info/40',
'https://p7ing.com/news_info/37',
'https://p7ing.com/news_info/30',
'https://p7ing.com/news_info/7',
'https://p7ing.com/news_info/67',
'https://p7ing.com/news_info/66',
'https://p7ing.com/news_info/65',
'https://p7ing.com/news_info/61',
'https://p7ing.com/news_info/60',
'https://p7ing.com/news_info/59',
'https://p7ing.com/news_info/55',
'https://p7ing.com/news_info/54',
'https://p7ing.com/news_info/53',
'https://p7ing.com/news_info/52',
'https://p7ing.com/news_info/51',
'https://p7ing.com/news_info/47',
'https://p7ing.com/news_info/46',
'https://p7ing.com/news_info/45',
'https://p7ing.com/news_info/44',
'https://p7ing.com/news_info/43',
'https://p7ing.com/news_info/42',
'https://p7ing.com/news_info/41',
'https://p7ing.com/news_info/31',
'https://p7ing.com/news_info/29',
'https://p7ing.com/news_info/28',
);
$api = 'http://data.zz.baidu.com/urls?site=https://p7ing.com&token=RmuvaatxbY5Agn4H';
$ch = curl_init();
$options =  array(
    CURLOPT_URL => $api,
    CURLOPT_POST => true,
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_POSTFIELDS => implode("\n", $urls),
    CURLOPT_HTTPHEADER => array('Content-Type: text/plain'),
);
curl_setopt_array($ch, $options);
$result = curl_exec($ch);
echo $result;